//! Property tests for [`dry_core::comparison::jaccard`] and the
//! [`dry_core::comparison::compare`] two-pass engine.
//!
//! Covers the load-bearing invariants from the PR 6 issue + AGENTS.md
//! "Comparison algorithm contract":
//!
//! - Jaccard is reflexive on non-empty input (`J(A, A) == 1.0`).
//! - Jaccard is symmetric (`J(A, B) == J(B, A)`).
//! - Jaccard never panics on any input, including either side empty.
//! - Jaccard's score lies in `[0.0, 1.0]` for any input.
//! - The sliding-window break math: if the inner loop breaks at `j`
//!   over the **sorted-by-set-size** projection, no later `k > j`
//!   clears `threshold`. Tested against `|fingerprint_set|` rather
//!   than `node_count` — the engine's algorithmic primitive is set
//!   size; `node_count` is a heuristic proxy with a documented
//!   accuracy gap (see module doc).
//! - Hash-bucket clustering: forms in the same emitted exact-match
//!   `Match` have structurally-equal `fingerprint_set`.
//! - `compare()` is idempotent: same input + threshold yields a
//!   byte-equal `Vec<Match>` across invocations.
//!
//! Regression files generated by `proptest` live in
//! `crates/dry-core/proptest-regressions/` and are committed (never
//! gitignored) per `AGENTS.md`.

use std::collections::{HashMap, HashSet};

use dry_core::comparison::{compare, compare_with_paths, jaccard};
use dry_core::domain::{FilePath, FormKind, LineColumn, Match, NormalizedForm, Span, Tier};
use proptest::prelude::*;

/// Strategy for an arbitrary fingerprint set. Bounded element range
/// (`0..256`) so collisions and overlaps appear with reasonable
/// frequency; the set size is up to 24 elements (smaller than that
/// keeps proptest's iteration budget reasonable while still covering
/// the algorithmic edges).
fn arb_fingerprint_set() -> impl Strategy<Value = HashSet<u64>> {
    prop::collection::hash_set(0u64..256, 0..24)
}

/// Strategy for a [`NormalizedForm`] whose `node_count` equals the
/// fingerprint-set size — the canonical case where the break-math
/// invariant holds exactly. Spans and the `FormKind` are
/// deterministic stubs (the engine doesn't read them as part of the
/// comparison primitive).
fn arb_form_with_set_size_node_count() -> impl Strategy<Value = NormalizedForm> {
    arb_fingerprint_set().prop_map(|fps| {
        let nc = u32::try_from(fps.len()).unwrap_or(u32::MAX);
        make_form_with_node_count(fps, nc)
    })
}

fn make_form_with_node_count(fps: HashSet<u64>, node_count: u32) -> NormalizedForm {
    NormalizedForm::new(
        FormKind::Production,
        fps,
        Span::try_new(LineColumn::new(1, 0), LineColumn::new(1, 0)).unwrap(),
        node_count,
        1,
    )
}

/// Unique synthetic path per input index — gives every form a unique
/// wire identity so emitted `FormRef`s can be mapped back to input
/// forms (`f<i>.rs` -> `forms[i]`) in the clustering properties below.
fn unique_paths(n: usize) -> Vec<FilePath> {
    (0..n)
        .map(|i| FilePath::from(std::path::PathBuf::from(format!("f{i:04}.rs"))))
        .collect()
}

/// Map an emitted `FormRef` file back to its input index (inverse of
/// [`unique_paths`]).
fn index_of_file(file: &str) -> usize {
    file.strip_prefix('f')
        .and_then(|s| s.strip_suffix(".rs"))
        .and_then(|s| s.parse().ok())
        .expect("FormRef file must be a unique_paths() synthetic path")
}

/// Reference pair set for the edge-conservation property, computed
/// brute-force from the input. With `node_count == |fingerprint_set|`
/// (the canonical generator), the sliding-window proxy break is exact
/// — a pruned pair provably has `J < t` — so the reference is the
/// complete ground truth for what the engine must represent:
///
/// - **exact pairs**: equal non-empty fingerprint sets (covered by a
///   Pass 1 n-ary match);
/// - **near pairs**: both forms unclaimed by Pass 1 (no equal-set
///   partner anywhere), sets unequal, `J >= t`.
///
/// Pairs where exactly one side is Pass-1-claimed are the documented
/// cross-tier-leakage gap — excluded here as they are in the engine.
fn reference_pairs(forms: &[NormalizedForm], threshold: f64) -> HashSet<(usize, usize)> {
    let claimed: Vec<bool> = (0..forms.len())
        .map(|i| {
            !forms[i].fingerprint_set.is_empty()
                && (0..forms.len())
                    .any(|j| j != i && forms[j].fingerprint_set == forms[i].fingerprint_set)
        })
        .collect();
    let mut pairs = HashSet::new();
    for i in 0..forms.len() {
        for j in (i + 1)..forms.len() {
            if forms[i].fingerprint_set.is_empty() || forms[j].fingerprint_set.is_empty() {
                continue;
            }
            let exact_pair = forms[i].fingerprint_set == forms[j].fingerprint_set;
            let near_pair = !exact_pair
                && !claimed[i]
                && !claimed[j]
                && jaccard(&forms[i].fingerprint_set, &forms[j].fingerprint_set) >= threshold;
            if exact_pair || near_pair {
                pairs.insert((i, j));
            }
        }
    }
    pairs
}

/// All member pairs derivable from an emitted match, as input-index
/// pairs, counted with multiplicity.
fn derived_pairs(matches: &[Match]) -> HashMap<(usize, usize), usize> {
    let mut pairs: HashMap<(usize, usize), usize> = HashMap::new();
    for m in matches {
        let idx: Vec<usize> = m
            .forms
            .iter()
            .map(|f| index_of_file(&f.file.to_string()))
            .collect();
        for (pos, &a) in idx.iter().enumerate() {
            for &b in &idx[pos + 1..] {
                let key = if a < b { (a, b) } else { (b, a) };
                *pairs.entry(key).or_insert(0) += 1;
            }
        }
    }
    pairs
}

proptest! {
    /// `J(A, A) == 1.0` on any non-empty input.
    #[test]
    fn jaccard_reflexive_on_non_empty(a in arb_fingerprint_set()) {
        prop_assume!(!a.is_empty());
        prop_assert!((jaccard(&a, &a) - 1.0).abs() < f64::EPSILON);
    }

    /// `J(A, B) == J(B, A)` for any inputs.
    #[test]
    fn jaccard_symmetric(a in arb_fingerprint_set(), b in arb_fingerprint_set()) {
        let ab = jaccard(&a, &b);
        let ba = jaccard(&b, &a);
        prop_assert!((ab - ba).abs() < f64::EPSILON);
    }

    /// Score is always in `[0.0, 1.0]`.
    #[test]
    fn jaccard_bounded_in_unit_interval(
        a in arb_fingerprint_set(),
        b in arb_fingerprint_set(),
    ) {
        let s = jaccard(&a, &b);
        prop_assert!((0.0..=1.0).contains(&s), "score {} out of bounds", s);
    }

    /// `jaccard` never panics on any input — including either side empty.
    #[test]
    fn jaccard_never_panics(a in arb_fingerprint_set(), b in arb_fingerprint_set()) {
        // Exercise both orders and the empty-vs-* cases.
        let _ = jaccard(&a, &b);
        let _ = jaccard(&b, &a);
        let empty: HashSet<u64> = HashSet::new();
        let _ = jaccard(&a, &empty);
        let _ = jaccard(&empty, &a);
        let _ = jaccard(&empty, &empty);
    }

    /// Break-math invariant — exact form.
    ///
    /// Tested against `|fingerprint_set|` directly, not against
    /// `node_count`. The Jaccard upper bound is:
    ///
    ///     J(A, B) <= min(|A|,|B|) / max(|A|,|B|)
    ///
    /// So for threshold `t`, if `max(|A|, |B|) > min(|A|, |B|) / t`,
    /// then `J(A, B) < t`. The engine uses `node_count` as a proxy
    /// because the sort is O(N log N) on `u32`; `node_count` may
    /// over-estimate `|fingerprint_set|` (per-leaf vs per-subform —
    /// see the O8 ADR), so the engine's break is conservative but
    /// the underlying math the algorithm relies on is what's
    /// tested here.
    #[test]
    fn jaccard_break_math_holds_against_set_size(
        a in arb_fingerprint_set(),
        b in arb_fingerprint_set(),
        threshold in 0.1f64..=0.99,
    ) {
        let min_size = a.len().min(b.len());
        let max_size = a.len().max(b.len());
        // Skip degenerate inputs (an empty set forces J = 0.0 by
        // the empty-set policy; the break math is trivially satisfied).
        prop_assume!(min_size > 0);
        // Skip when `min_size / threshold` overflows the u32 range
        // we sample over — vacuously safe.
        #[allow(clippy::cast_precision_loss)]
        let bound = (min_size as f64) / threshold;
        if (max_size as f64) > bound {
            let s = jaccard(&a, &b);
            prop_assert!(
                s < threshold,
                "break math: max_size={} > min_size/threshold={}, but jaccard={} >= threshold={}",
                max_size,
                bound,
                s,
                threshold,
            );
        }
    }

    /// `compare()` is idempotent.
    #[test]
    fn compare_is_idempotent(
        forms in prop::collection::vec(arb_form_with_set_size_node_count(), 0..10),
        threshold in 0.5f64..0.99,
    ) {
        let r1 = compare(&forms, threshold);
        let r2 = compare(&forms, threshold);
        prop_assert_eq!(r1, r2);
    }

    /// Every emitted match carries `score` in the half-open
    /// interval `[threshold, 1.0]`. Pass 1 emits exactly 1.0;
    /// Pass 2 emits >= threshold.
    #[test]
    fn every_emitted_match_score_clears_the_threshold(
        forms in prop::collection::vec(arb_form_with_set_size_node_count(), 0..10),
        threshold in 0.5f64..0.99,
    ) {
        let matches = compare(&forms, threshold);
        for m in &matches {
            prop_assert!(
                m.score >= threshold,
                "match score {} must be >= threshold {}",
                m.score,
                threshold,
            );
            prop_assert!(
                m.score <= 1.0,
                "match score {} must be <= 1.0",
                m.score,
            );
        }
    }

    /// Tier assignment follows the floor table:
    /// - score == 1.0 -> AutoRefactor (Pass 1)
    /// - score >= 0.95 -> AutoRefactor
    /// - score >= 0.85 -> ReviewFirst
    /// - else (>= threshold) -> Advisory
    #[test]
    fn tier_assignment_follows_floor_table(
        forms in prop::collection::vec(arb_form_with_set_size_node_count(), 0..10),
        threshold in 0.5f64..0.99,
    ) {
        let matches = compare(&forms, threshold);
        for m in &matches {
            let expected_tier = if m.score >= 0.95 {
                Tier::AutoRefactor
            } else if m.score >= 0.85 {
                Tier::ReviewFirst
            } else {
                Tier::Advisory
            };
            prop_assert_eq!(
                m.tier,
                expected_tier,
                "score {} must route to tier {:?}, got {:?}",
                m.score,
                expected_tier,
                m.tier,
            );
        }
    }

    /// Clique guarantee (dry-rs#97, adr-cluster-output ADR-1): every
    /// pair of forms inside ANY emitted match — Pass 1 n-ary exact
    /// cluster, Pass 3 carved clique, or residual pair — has Jaccard
    /// `>= threshold`. No member is ever a below-threshold
    /// transitive hanger-on.
    #[test]
    fn every_intra_match_pair_clears_the_threshold(
        forms in prop::collection::vec(arb_form_with_set_size_node_count(), 0..12),
        threshold in 0.5f64..0.99,
    ) {
        let paths = unique_paths(forms.len());
        let matches = compare_with_paths(&forms, &paths, threshold);
        for m in &matches {
            let idx: Vec<usize> = m
                .forms
                .iter()
                .map(|f| index_of_file(&f.file.to_string()))
                .collect();
            for (pos, &a) in idx.iter().enumerate() {
                for &b in &idx[pos + 1..] {
                    let j = jaccard(&forms[a].fingerprint_set, &forms[b].fingerprint_set);
                    prop_assert!(
                        j >= threshold,
                        "intra-match pair ({}, {}) has J={} below threshold={} in {:?}",
                        a, b, j, threshold, m,
                    );
                }
            }
        }
    }

    /// Edge conservation (adr-cluster-output ADR-2): the pairs
    /// derivable from the output — every member pair of every match,
    /// counted with multiplicity — are EXACTLY the reference pairs
    /// (equal-set pairs + unclaimed `J >= t` pairs), each exactly
    /// once. Clustering is a lossless regrouping of the pairwise
    /// output: nothing dropped, nothing invented, nothing
    /// double-counted.
    #[test]
    fn output_conserves_every_edge_exactly_once(
        forms in prop::collection::vec(arb_form_with_set_size_node_count(), 0..12),
        threshold in 0.5f64..0.99,
    ) {
        let paths = unique_paths(forms.len());
        let matches = compare_with_paths(&forms, &paths, threshold);
        let derived = derived_pairs(&matches);
        let reference = reference_pairs(&forms, threshold);

        for (&pair, &count) in &derived {
            prop_assert!(
                reference.contains(&pair),
                "output invented pair {:?} (J below threshold or claimed-form leak)",
                pair,
            );
            prop_assert_eq!(
                count, 1,
                "pair {:?} represented {} times; edge conservation requires exactly once",
                pair, count,
            );
        }
        for &pair in &reference {
            prop_assert!(
                derived.contains_key(&pair),
                "output dropped reference pair {:?}",
                pair,
            );
        }
    }

    /// Permutation stability (adr-cluster-output ADR-4): permuting
    /// the input order (forms and paths together) leaves the emitted
    /// match set unchanged — membership, scores, and tiers derive
    /// from form identities, never from input indices. (Forms here
    /// have unique file identities via `unique_paths`; the identity
    /// tie-break chain only falls back to the input index when
    /// identities collide.)
    #[test]
    fn cluster_membership_is_permutation_stable(
        forms in prop::collection::vec(arb_form_with_set_size_node_count(), 0..12),
        rotation in 0usize..12,
        reversed in any::<bool>(),
        threshold in 0.5f64..0.99,
    ) {
        let paths = unique_paths(forms.len());

        let canonical = |ms: &[Match]| -> Vec<(Vec<String>, u64, Tier)> {
            let mut v: Vec<(Vec<String>, u64, Tier)> = ms
                .iter()
                .map(|m| {
                    let mut files: Vec<String> =
                        m.forms.iter().map(|f| f.file.to_string()).collect();
                    files.sort();
                    (files, m.score.to_bits(), m.tier)
                })
                .collect();
            v.sort();
            v
        };

        let baseline = canonical(&compare_with_paths(&forms, &paths, threshold));

        let mut indices: Vec<usize> = (0..forms.len()).collect();
        let len = indices.len();
        if len > 0 {
            indices.rotate_left(rotation % len);
        }
        if reversed {
            indices.reverse();
        }
        let permuted_forms: Vec<NormalizedForm> =
            indices.iter().map(|&i| forms[i].clone()).collect();
        let permuted_paths: Vec<FilePath> =
            indices.iter().map(|&i| paths[i].clone()).collect();
        let permuted = canonical(&compare_with_paths(&permuted_forms, &permuted_paths, threshold));

        prop_assert_eq!(baseline, permuted);
    }

    /// Matches are sorted by `(forms[0].file, forms[0].span.start,
    /// -score)` in the returned vector.
    #[test]
    fn output_is_sorted_canonically(
        forms in prop::collection::vec(arb_form_with_set_size_node_count(), 0..12),
        threshold in 0.5f64..0.99,
    ) {
        let matches = compare(&forms, threshold);
        for w in matches.windows(2) {
            let a = &w[0];
            let b = &w[1];
            // Both matches are emitted with at least 2 forms (Pass
            // 1 n-ary or Pass 2 binary), so `forms[0]` is always
            // present.
            let af = &a.forms[0];
            let bf = &b.forms[0];
            // Lexicographic order on (file, span.start) — if equal,
            // the score (descending) is the tie-breaker.
            let prefix_order = (af.file.clone(), af.span.start)
                .cmp(&(bf.file.clone(), bf.span.start));
            match prefix_order {
                std::cmp::Ordering::Less => {} // strictly increasing — OK
                std::cmp::Ordering::Equal => {
                    // Within the same (file, span.start), score must
                    // be descending.
                    prop_assert!(
                        a.score >= b.score,
                        "tied prefix; expected score {} >= {}",
                        a.score,
                        b.score,
                    );
                }
                std::cmp::Ordering::Greater => {
                    prop_assert!(
                        false,
                        "sort violation: {:?} should not precede {:?}",
                        af,
                        bf,
                    );
                }
            }
        }
    }
}
